title: Team Meshbits
description: >- # this means to ignore newlines until "baseurl:"
  This document is to describe who we are, our passion and commitment to the
  Komodo project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-theme-hacker
markdown: kramdown
show_downloads: false
google_analytics: UA-115540513-1
#github_organisation: https://github.com/meshbits
#email:
github: [metadata]
